name: ecommerce_app
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


  #---------------PACKAGES----------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.2+1
  url_launcher: ^6.1.12
  flutter_native_splash: ^1.1.0
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  # icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1
  # Product Specific

# ---------------/ PACKAGES END -------------#
dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  #--------------- LOCAL ASSETS--------#
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/on_boarding_images/
    - assets/images/categories/
    - assets/images/products/
    - assets/images/banners/
    - assets/logos/brands/


  #---------logical fonts--------------#
#  fonts:
#    - family: Poppins
#      fonts:
#        - asset: assets/fonts/Poppins-Light.ttf
#          weight: 300
#        - asset:  assets/fonts/Poppins-Regular.ttf
#          weight: 400
#        - asset:  assets/fonts/Poppins

  


  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
